MERGE SORT


In [ ]:
def merge_sort(arr):
  if len(arr) <= 1:
    return arr
  mid = len(arr) // 2
  left = arr[:mid]
  right = arr[mid:]
  left = merge_sort(left)
  right = merge_sort(right)
  return merge(left, right)
def merge(left, right):
  result = []
  i = j = 0
  while i < len(left) and j < len(right):
    if left[i] < right[j]:
      result.append(left[i])
      i += 1
    else:
      result.append(right[j])
      j += 1
  result.extend(left[i:])
  result.extend(right[j:])
  return result
arr = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_arr = merge_sort(arr)
print(sorted_arr)

[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]


In [ ]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        merge_sort(left_half)
        merge_sort(right_half)

        i = j = k = 0

        # Merge the two sorted halves
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

# Example usage:
arr = [38, 27, 43, 3,3, 9, 82, 10]
print("Original array:", arr)
merge_sort(arr)
print("Sorted array:", arr)

Original array: [38, 27, 43, 3, 3, 9, 82, 10]
Sorted array: [3, 3, 9, 10, 27, 38, 43, 82]


QUICK SORT

In [ ]:
def quick_sort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quick_sort(left) + middle + quick_sort(right)
#example
arr = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_arr = quick_sort(arr)
print(sorted_arr)

[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]


 Given a sorted array and a number X, search two elements
of the array such that their sum is X. Expected time
complexity is O(n2 ) and O(n).

In [ ]:
#Solution 1: O(n^2) time complexity
def find_pair_in_sorted_array_O_n_square(arr, X):
  for i in range(len(arr)):
    complement = X - arr[i]
  for j in range(i + 1, len(arr)):
    if arr[j] == complement:
      return (arr[i], arr[j])
  return None
arr = [1, 3, 4, 5, 7, 9]
X = 12

pair1 = find_pair_in_sorted_array_O_n_square(arr, X)
pair2 = find_pair_in_sorted_array_O_n_square(arr, X)
print(f"Pair 1: {pair1}") # Output: Pair 1: (4, 8)
print(f"Pair 2: {pair2}") # Output: Pair 2: (4, 8)


Pair 1: None
Pair 2: None


In [ ]:
#Solution 2: O(n) time complexity
def find_pair_in_sorted_array_O_n(arr, X):
  complements = {}
  for i, num in enumerate(arr):
    complement = X - num
    if complement in complements:
      return (num, complement)
    complements[num] = i
  return None
#example
arr = [1, 3, 4, 5, 7, 9]
X = 12
pair1 = find_pair_in_sorted_array_O_n(arr, X)
pair2 = find_pair_in_sorted_array_O_n(arr, X)
print(f"Pair 1: {pair1}") # Output: Pair 1: (4, 8)
print(f"Pair 2: {pair2}") # Output: Pair 2: (4, 8)

Pair 1: (7, 5)
Pair 2: (7, 5)


Given a sorted array and a number x, write a function that
counts the occurrences of x in the array. Expected time
complexity is O(n) and O(logn).


In [ ]:
#Solution 1: O(n) time complexity
def count_occurrences_in_sorted_array_O_n(arr, x):
  count = 0
  for num in arr:
    if num == x:
      count += 1
  return count
#example
arr = [1, 3, 4, 5, 7, 9, 9, 9, 11]
x = 9
count1 = count_occurrences_in_sorted_array_O_n(arr, x)
count2 = count_occurrences_in_sorted_array_O_n(arr, x)
print(f"Count 1: {count1}") # Output: Count 1: 3
print(f"Count 2: {count2}") # Output: Count 2: 3


Count 1: 3
Count 2: 3


In [ ]:
def first_occurrence(arr, x):
    low = 0
    high = len(arr) - 1
    first = -1

    while low <= high:
        mid = low + (high - low) // 2
        if arr[mid] == x:
            first = mid
            high = mid - 1
        elif arr[mid] < x:
            low = mid + 1
        else:
            high = mid - 1

    return first

def last_occurrence(arr, x):
    low = 0
    high = len(arr) - 1
    last = -1

    while low <= high:
        mid = low + (high - low) // 2
        if arr[mid] == x:
            last = mid
            low = mid + 1
        elif arr[mid] < x:
            low = mid + 1
        else:
            high = mid - 1


        return last


def count_occurrences(arr, x):
    first = first_occurrence(arr, x)
    last = last_occurrence(arr, x)

    if first == -1 or last == -1:
        return 0
    else:
        return last - first + 1

# Example usage:
arr = [1, 2, 2, 2, 3, 3, 4, 4, 5, 5]
x = 3
print("Occurrences of", x, ":", count_occurrences(arr, x))

Occurrences of 3 : 1


 Implement Binary Search using Divide and Conquer.

In [ ]:
def binary_search(arr, low, high, target):
  if low > high:
    return -1
  mid = (low + high) // 2
  if arr[mid] == target:
    return mid
  elif arr[mid] < target:
    return binary_search(arr, mid + 1, high, target)
  else:
    return binary_search(arr, low, mid - 1, target)
#example
arr = [1, 3, 4, 5, 7, 9, 11]
x = 9
index = binary_search(arr, 0, len(arr) - 1, x)
if index != -1:
  print(f"{x} found at index {index}")
else:
  print(f"{x} not found in the array")

9 found at index 5


 Implement a greedy algorithm to solve the fractional knapsack problem.

In [ ]:
def fractional_knapsack(capacity, items):
  items.sort(key=lambda x: x[1]/x[0], reverse=True)
  total_value = 0
  for item in items:
    if capacity >= item[0]:
      capacity -= item[0]
      total_value += item[1]
    else:
      total_value += capacity * (item[1]/item[0])
      break
  return total_value
#example
items = [(2, 10), (3, 40), (1, 30), (4, 50)]
capacity = 6
value = fractional_knapsack(capacity, items)
print(f"Maximum value: {value}")

Maximum value: 95.0


7. Find the largest and smallest number simultaneously in an array using Divide & Conquer Principle

In [ ]:
def find_min_max(arr, low, high):
  if low == high:
    return (arr[low], arr[low])
  mid = (low + high) // 2
  left_min, left_max = find_min_max(arr, low, mid)
  right_min, right_max = find_min_max(arr, mid + 1, high)
  return (min(left_min, right_min), max(left_max, right_max))
#example
arr = [1, 4, 2, 6, 8, 3, 5]
min_num, max_num = find_min_max(arr, 0, len(arr) - 1)
print(f"Smallest number: {min_num}")
print(f"Largest number: {max_num}")

Smallest number: 1
Largest number: 8


8. Implement the greedy algorithm to solve the problem of the Job Sequencing with deadlines

In [ ]:
def job_sequencing_with_deadlines(jobs):
    # Sort jobs based on their profits in descending order
    jobs.sort(key=lambda x: x[2], reverse=True)

    # Find the maximum deadline among all jobs
    max_deadline = max(jobs, key=lambda x: x[1])[1]

    # Initialize the schedule with slots up to the maximum deadline
    schedule = [None] * (max_deadline + 1)

    total_profit = 0
    for job in jobs:
        deadline = job[1]
        # Find an available slot before the deadline
        while deadline > 0 and schedule[deadline] is not None:
            deadline -= 1
        if deadline > 0:
            schedule[deadline] = job[0]  # Assign the job to the slot
            total_profit += job[2]  # Add the job's profit to total profit

    return schedule, total_profit


# Example usage:
jobs_list = [('J1', 2, 40), ('J2', 1, 35), ('J3', 3, 30), ('J4', 1, 25), ('J5', 3, 20)]
schedule_result, total_profit_result = job_sequencing_with_deadlines(jobs_list)
print("Job Schedule:", schedule_result)
print("Total Profit:", total_profit_result)

Job Schedule: [None, 'J2', 'J1', 'J3']
Total Profit: 105


9. Apply Strassen’s Matrix Multiplication strategy for odd dimensional square matrices.


In [ ]:
import numpy as np

def pad_matrix(matrix):
    n = len(matrix)
    new_size = n + 1 if n % 2 == 1 else n  # Ensure even size
    padded_matrix = np.pad(matrix, ((0, new_size - n), (0, new_size - n)), mode='constant')
    return padded_matrix

def trim_matrix(matrix, original_size):
    return matrix[:original_size, :original_size]

def strassen_multiply(A, B):
    n = len(A)

    # Base case: If matrices are small, perform regular matrix multiplication
    if n <= THRESHOLD:
        return np.dot(A, B)

    # Pad matrices if necessary to make them even-sized
    if n % 2 == 1:
        A = pad_matrix(A)
        B = pad_matrix(B)

    # Partition matrices
    half_size = n // 2
    A11, A12 = A[:half_size, :half_size], A[:half_size, half_size:]
    A21, A22 = A[half_size:, :half_size], A[half_size:, half_size:]
    B11, B12 = B[:half_size, :half_size], B[:half_size, half_size:]
    B21, B22 = B[half_size:, :half_size], B[half_size:, half_size:]

    # Compute intermediate matrices
    M1 = strassen_multiply(A11 + A22, B11 + B22)
    M2 = strassen_multiply(A21 + A22, B11)
    M3 = strassen_multiply(A11, B12 - B22)
    M4 = strassen_multiply(A22, B21 - B11)
    M5 = strassen_multiply(A11 + A12, B22)
    M6 = strassen_multiply(A21 - A11, B11 + B12)
    M7 = strassen_multiply(A12 - A22, B21 + B22)

    # Combine intermediate matrices to get result
    C11 = M1 + M4 - M5 + M7
    C12 = M3 + M5
    C21 = M2 + M4
    C22 = M1 - M2 + M3 + M6

    # Combine result submatrices into final result
    result = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))

    # Trim extra rows/columns if matrices were padded
    if n % 2 == 1:
        result = trim_matrix(result, n)

    return result

# Example usage:
THRESHOLD = 64  # Define threshold for base case
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = strassen_multiply(A, B)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


KMP String Matching: Given a text txt[0..n-1] and a pattern pat[0..m-1], write a function search(char pat[], char txt[]) that prints all occurrences of pat[] in txt[]. You may assume that n > m. Text: A A B A A C A A D A A B A A B A
Pattern: A A B A.

In [ ]:
def compute_lps_array(pat, m):
    lps = [0] * m
    length = 0
    i = 1
    while i < m:
        if pat[i] == pat[length]:
            length += 1
            lps[i] = length
            i += 1
        else:
            if length != 0:
                length = lps[length - 1]
            else:
                lps[i] = 0
                i += 1
    return lps

def kmp_search(pat, txt):
    n = len(txt)
    m = len(pat)

    lps = compute_lps_array(pat, m)

    i = 0
    j = 0
    while i < n:
        if pat[j] == txt[i]:
            i += 1
            j += 1
        if j == m:
            print("Pattern found at index", i - j)
            j = lps[j - 1]
        elif i < n and pat[j] != txt[i]:
            if j != 0:
                j = lps[j - 1]
            else:
                i += 1

# Example usage:
txt = "AABAACAADAAABAAABAA"
pat = "AAB"
kmp_search(pat, txt)

Pattern found at index 0
Pattern found at index 10
Pattern found at index 14


 Implement DP strategy to solve the Traveling Salesman Problem (TSP).

In [ ]:
import sys

def tsp_dp(graph):
    n = len(graph)
    # Initialize the DP table with all nodes and no edges visited
    dp = [[None] * (1 << n) for _ in range(n)]
    start = 0  # Start from the first city

    # Helper function to recursively find the shortest path
    def dfs(node, visited):
        # Base case: If all cities are visited, return the distance to start city
        if visited == (1 << n) - 1:
            return graph[node][start]
        # If already computed, return the result
        if dp[node][visited] is not None:
            return dp[node][visited]

        # Initialize the minimum distance to infinity
        min_dist = sys.maxsize
        for next_node in range(n):
            # If next_node is not visited yet
            if (visited & (1 << next_node)) == 0:
                # Calculate the distance to next_node and add it to the total distance
                dist = graph[node][next_node] + dfs(next_node, visited | (1 << next_node))
                # Update the minimum distance
                min_dist = min(min_dist, dist)

        # Memoize the result
        dp[node][visited] = min_dist
        return min_dist

    # Start the recursive search from the start node
    return dfs(start, 1 << start)

# Example usage:
graph = [
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
]
print("Shortest path length:", tsp_dp(graph))

Shortest path length: 80
